"""empty message

Revision ID: 5f13a94b8200
Revises: 
Create Date: 2021-08-03 18:38:24.627837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f13a94b8200'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_devices',
    sa.Column('token_id', sa.String(length=500), nullable=True),
    sa.Column('device_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('device_readings',
    sa.Column('reading_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('moisture_sensor', sa.Integer(), nullable=True),
    sa.Column('temperature_sensor', sa.Integer(), nullable=True),
    sa.Column('light_sensor', sa.Integer(), nullable=True),
    sa.Column('reading_time', sa.DateTime(), nullable=True),
    sa.Column('received_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('device_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['users_devices.device_id'], ),
    sa.PrimaryKeyConstraint('reading_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_readings')
    op.drop_table('users_devices')
    # ### end Alembic commands ###
